// program where the user has to guess a number generated by a program
let stage = 1;
let userName = prompt('Enter your username');
let award =0;
  function setRange(random, number) {
    let predict = parseInt(prompt('predict a number from given range'));
    

    // generating a random integer from 1 to 2
    let answer = Math.floor(Math.random() *(random - number + 1)) + number;

    if(predict == answer ){
      number = number + 1;
      stage = stage + 1;
      award = award + 1;
      console.log(`You have guess right ${userName} YOU CAN you can move to the next stage and you have earn ${award} point`);
      setRange(random,number);
      
    }else{
      console.log(`You have guess wrong ${userName} the answer is ${answer}`);
    }
    }

setRange(1,2);
